# playbooks\full_pipeline.yml
- name: ğŸ§© Instalar kubeseal
  import_playbook: install_kubeseal.yml

- name: ğŸš€ Instalar Sealed Secrets Controller
  import_playbook: install_sealed_secrets.yml

- name: ğŸ” Renderizar y cifrar secretos
  import_playbook: render_and_encrypt_secrets.yml