# playbooks/generate_base_secrets.yml
- name: ğŸ› ï¸ Generar YAML base de secretos Opaque
  hosts: localhost
  become: false
  gather_facts: false

  vars_files:
    - ../vars/main.yml

  tasks:
    - name: ğŸ“ Crear directorio de templates
      file:
        path: secrets-templates
        state: directory
        mode: '0755'

    - name: ğŸ“ Secret Jenkins
      copy:
        content: |
          apiVersion: v1
          kind: Secret
          metadata:
            name: jenkins-admin-secret
            namespace: ci
          type: Opaque
          data:
            username: {{ jenkins_auth_user | b64encode }}
            password: {{ jenkins_auth_pass | b64encode }}
        dest: secrets-templates/jenkins-admin-secret.yaml

    - name: ğŸ“ Secret Grafana
      copy:
        content: |
          apiVersion: v1
          kind: Secret
          metadata:
            name: grafana-admin-secret
            namespace: monitoring
          type: Opaque
          data:
            username: {{ grafana_auth_user | b64encode }}
            password: {{ grafana_auth_pass | b64encode }}
        dest: secrets-templates/grafana-admin-secret.yaml

    - name: ğŸ“ Secret Prometheus
      copy:
        content: |
          apiVersion: v1
          kind: Secret
          metadata:
            name: prometheus-basic-auth
            namespace: monitoring
          type: Opaque
          data:
            auth: {{ (prometheus_auth_user + ':' + prometheus_auth_pass) | b64encode }}
        dest: secrets-templates/prometheus-basic-auth.yaml

    - name: ğŸ“ Secret ArgoCD
      copy:
        content: |
          apiVersion: v1
          kind: Secret
          metadata:
            name: argocd-secret
            namespace: argocd
          type: Opaque
          data:
            username: {{ argocd_auth_user | b64encode }}
            password: {{ argocd_auth_pass | b64encode }}
        dest: secrets-templates/argocd-secret.yaml

    - name: ğŸ“ Secret Longhorn
      copy:
        content: |
          apiVersion: v1
          kind: Secret
          metadata:
            name: longhorn-ui-secret
            namespace: longhorn-system
          type: Opaque
          data:
            username: {{ longhorn_auth_user | b64encode }}
            password: {{ longhorn_auth_pass | b64encode }}
        dest: secrets-templates/longhorn-ui-secret.yaml